# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://192.144.207.22:3306/forum1.0?characterEncoding=utf-8
      #      username: root
      #      password: 123456
      url: jdbc:mysql://127.0.0.1:3306/forum1.0?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:       # 密码（默认为空）
    timeout: 6000ms # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  # 配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    # 虚拟机host 可以不设置,使用server默认host
    virtual-host: /
    # 确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    # 确认消息已发送到队列(Queue)
    publisher-returns: true

# mybatis
mybatis-plus:
  mapper-locations: classpath*:dao/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.forum.modules.*.dao
  global-config:
    db-config:
      # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 驼峰下划线转换
      column-underline: true
      # 刷新mapper 调试神器
      refresh-mapper: false
      # 数据库大写下划线转换
      # capital-mode: true
      # Sequence序列接口实现类配置
      # key-generator: com.baomidou.base.incrementer.OracleKeyGenerator
      # 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    jdbc-type-for-null: 'VARCHAR'
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

framework:
  redis:
    open: true # 是否开启缓存  true开启   false关闭

logging:
  level: debug
  level.com.forum: debug
  db: debug
  error: debug
  file: D:/logs/log_log4j

permission-config:
  perms:
    - key: /login/user
      value: anon
    - key: /login/logout
      value: anon
    - key: /**
      value: jwt

